#!/bin/sh

#
# This checks job_status.log for lines indicating failure/warning and
# notifies the dev listserv when errors are found.
# Custom exclusion regexps can be added or toggled below to remove prevent
# matching lines from being reported. job_status.log is cleared when this
# script runs, but the most recent 1000 lines of log are retained in
# job_status.log.old
#


exclude_lines() {
  errors_to_report=$(echo -e "$errors_to_report" | grep -v "$1")  
}

work_dir="/data/util/logs"          # production
#work_dir="/home/endeca/logs"       # testing
this_script="/data/util/jobstatuslog_error_mailer.sh"
timestamp=$(date "+%F %T")
log_newlines="job_status.log~"

# dev listserv email
listserv_email="searchtrlnmgrs@listserv.unc.edu" # production
#listserv_email="eres_cat@unc.edu"               # testing
# support contact
support_email="eres_cat@unc.edu"


cd $work_dir
touch job_status.log._tmp
mv job_status.log._tmp job_status.log --backup


# Exclude lines reporting success
#
# Toggling to line below would exclude explicit successes
#errors_to_report=$(grep -vi -e 'complete' -e 'succeed' $log_newlines)
#
# Toggling to line would include explicit errors
errors_to_report=$(grep -i -e 'fail' -e 'warn' $log_newlines)

###############################################
#
# Exclude further lines matching custom regexps
#
#   add or comment out custom exclusion rules as needed
#   the regexps are case sensitive
#   Example:
#     # expected until Odum provides working OAI feed -kms@unc
#     exclude_lines '^Dataverse Daily Delta Failed'
#

# failure should be reported by Nagios -kms@unc
exclude_lines '^Restarting tomcat'

# expected while Sunday morning baseline process runs -kms@unc
exclude_lines '^Deferring Partials'

# expected until Odum provides working OAI feed -kms@unc
exclude_lines '^Dataverse Daily Delta Failed'


#
# End exclusion
#
################################################


# send mail if errors
if [ "$errors_to_report" != "" ]; then
  errorcount=$(echo "$errors_to_report" | wc -l)
  header="There were $errorcount new errors found in: job_status.log
    This check ran at: $timestamp
    This email was generated by: $this_script
    Problems with this script? Notify $support_email
    Errors:\n\n"
  echo -e "$header$errors_to_report" | mail -s "Endeca Error Report: job_status.log" "$listserv_email"
fi

# append new log lines to job_status.log.old but keep only
# most recent 1000 lines
cat $log_newlines >> job_status.log.old
tail -n 1000 job_status.log.old > job_status.log.old._tmp
mv job_status.log.old._tmp job_status.log.old
rm -f job_status.log~
